FROM golang:alpine as builder

RUN apk update && apk add --no-cache git

WORKDIR /app

# Build the Go app
COPY /worker/ .
RUN go mod download 
RUN CGO_ENABLED=0 GOOS=linux go build -a -o main ./app/

# Start a new stage from scratch
FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/main .

# Expose port 8080 to the outside world
EXPOSE 8080

#Command to run the executable
CMD ["./main"]
