apiVersion: apps/v1 
kind: Deployment
metadata:
  name: maintenance-api
  labels:
    app: maintenance-api
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: maintenance-api
  template:
    metadata:
      labels:
        app: maintenance-api                              
    spec:
      containers:
      - name: maintenance-api 
        image: vitorbiten/maintenance-api
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        envFrom:
          - secretRef:
              name: secrets
---
apiVersion: v1  
kind: Service
metadata:
  name: maintenance-api
  labels:
    app: maintenance-api
spec:
  type: NodePort
  selector:
    app: maintenance-api
  ports: 
  - name: http
    port: 8080
    targetPort: 8080