apiVersion: v1
kind: Service
metadata:
  name: linode-service
  labels:
    app: maintenance-api
spec:
  type: LoadBalancer
  selector:
    app: maintenance-api
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080