name: Build and Deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push api
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: vitorbiten/maintenance-api:${{github.ref_name}}
          cache-from: type=registry,ref=user/app:${{github.ref_name}}
          cache-to: type=inline
      - name: Build and push worker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.worker
          push: true
          tags: vitorbiten/maintenance-worker:${{github.ref_name}}
          cache-from: type=registry,ref=user/app:${{github.ref_name}}
          cache-to: type=inline
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Kubernetes apply
        run: |
          sed -i'' -e 's,/maintenance-api,/maintenance-api:${{github.ref_name}},g' ./kubernetes/api-deployment.yaml
          kubectl apply -f ./kubernetes/api-deployment.yaml
          sed -i'' -e 's,/maintenance-api,/maintenance-api:${{github.ref_name}},g' ./kubernetes/worker-deployment.yaml
          kubectl apply -f ./kubernetes/worker-deployment.yaml
